[build]
  base = "fe"
  functions = "api"
  publish = "build"
  command = "CI=false npm run build"
[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200
[[redirects]]
  from     = "/api/*"
  to       = "/.netlify/functions/:splat"
  status   = 200